apiVersion: 1

datasources:
  - name: PostgreSQL-DWH
    type: postgres
    uid: postgres-dwh
    url: postgres-dwh:5432
    database: bitcoin
    user: analytics
    secureJsonData:
      password: analytics
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1500
    isDefault: true
    editable: true
